development:
  adapter: postgresql
  encoding: unicode
  database: demo_weixin_development
  pool: 5
  username: dbuser
  password: db.password

test:
  adapter: postgresql
  encoding: unicode
  database: demo_weixin_test
  pool: 5
  username: dbuser
  password: db.password

production:
  adapter: postgresql
  encoding: unicode
  database: demo_weixin_production
  pool: 5
  username: dbuser
  password: db.password
