development:
  adapter: postgresql
  encoding: unicode
  database: weixin_server_development
  pool: 5
  username: dbuser
  password: db.password

test:
  adapter: postgresql
  encoding: unicode
  database: weixin_server_test
  pool: 5
  username: dbuser
  password: db.password

production:
  adapter: postgresql
  encoding: unicode
  database: weixin_server_production
  pool: 5
  username: dbuser
  password: db.password
